### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by aliciapaz**
## Newsweek clone

For this project we created a clone of Newsweek site, using HTML, CSS/SASS and Bootstrap.

### Main features
- Bootstrap classes for main positioning and styling of the elements
- Grid system (flex) for responsiveness, with lg and md breakpoints
- For more detailed styling and customization, css/sass was used

### Desktop version
Desktop

### Small screen version 
mobile_live

### CODE REVIEW

**Review by abredi — CHANGES_REQUESTED** [review]
### Status: Require changes 🌳 ♲
Hi @ixboy and @aliciapaz, I am  [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR.  👏👏   I appreciate your hard work in replicating newsweek.com. Kindly fix the issues stated in the previous review. 

- [x] Fix background-position and width of the newsletter image
- [x] Fix the clustered footer links. Avoid list styles.
- [x]  The newsletter section and the subscribe section should have a full row separately on medium screens.
- [ ]  The Ad cards and sign-up form size do not resemble the source. They should have a fixed size similar to the source page.
- [ ] In medium screens, Featured Stories and Top Story including My Turn, Culture and Stories and, More Stories should be in two columns and side by side.


| Your Copy | Source | 
| :---:         |     :---:      |
| Screen Shot 2020-12-11 at 2 29 05 AM| Screen Shot 2020-12-11 at 2 29 28 AM
|Screen Shot 2020-12-11 at 2 30 24 AM| Screen Shot 2020-12-11 at 2 34 39 AM
|Screen Shot 2020-12-11 at 2 36 11 AM|Screen Shot 2020-12-11 at 2 37 34 AM |

 
Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Comment by aliciapaz** [comment]
Thank you for the code review. 
- Fixed newsletter, ad and sign up cards for medium screen
- Removed style on footer links
- Fixed positioning of the main content on medium screen

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @aliciapaz and @ixboy  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your clone looks like the original page and it is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [x] Fix the navbar on smaller screens (check screens less than 324px)

| Your clone | Original page |
| --- | --- |
|Screenshot from 2020-12-11 08-59-32 |Screenshot from 2020-12-11 08-58-33 |

:point_right: Could you see the difference :question: :question: :question: 

- [x] Fix the free `free signup` form on mobile screens (check screens less than 768px)

| Your clone | Original page |
| --- | --- |
|Screenshot from 2020-12-11 09-05-08|Screenshot from 2020-12-11 09-08-01|

:point_right: Could you see the difference :question: :question: :question: 

___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by aliciapaz** [comment]
Thank you very much for this code review.
- Fixed navbar on mobile screens
- Fixed signup form on screens smaller than 768px

mobile
signup

**Comment by mimipeshy** [comment]
## STATUS :CHANGES REQUIRED 🔴 ♻️ 

Hey team 👋 👋 , you guys are doing well so far, Your project looks really nice. However, i still have a request to make, don't feel tired or sad we just want you to be the best developers 😄 

- [ ]  On the mobile menu, the featured stories should appear right below the top story. This is followed by the debate section, more stories at last my turn, and the culture and travel section. Kindly check on this 😄 . 


That's all. 😄 , kindy submit another review when you are done

Regards
Peris Ndanu

**Comment by aliciapaz** [comment]
Thank you for the code review. 
- Fixed order of articles on mobile version

displaymobile

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @aliciapaz**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [x] you did well on the project, but you created separate html for each screen size and this is against the first rule of coding DRY (Don't repeat yourself). you must write one code for the 3 screen sizes. you can do that by taking advantage of bootstrap's layout classes ( rows and columns) found [here](https://getbootstrap.com/docs/4.5/layout/overview/) and [here](https://getbootstrap.com/docs/4.5/layout/grid/).

- [x] you can use [this ](https://github.com/mahmoud717/Microverse-newsweek) project as a reference. see how bootstraps col and row classes are implemented here.


---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Comment by aliciapaz** [comment]
Thanks for the review.
- Deleted the HTML element classed "mobile-version" and re-used some parts of the code only, as the project referenced did.

**Comment by mimipeshy** [comment]
## STATUS: APPROVED 🥳 👯 

Hello, 👋 👋 congratulations on completing this project. Its approved, go ahead and merge. Good luck in your next projects 😄 

Regards
Peris Ndsnu

**Pull request merged**
